"""empty message

Revision ID: 0669864d5f0f
Revises: c8791e26c482
Create Date: 2023-09-11 00:41:53.713480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0669864d5f0f'
down_revision = 'c8791e26c482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
