"""Added pass to test table

Revision ID: 148432d409ea
Revises: 
Create Date: 2023-07-21 20:26:20.075589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148432d409ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
