"""empty message

Revision ID: 175b6d442275
Revises: 404d2adc070c
Create Date: 2023-09-14 02:35:59.149345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175b6d442275'
down_revision = '404d2adc070c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
