"""empty message

Revision ID: 3d496e50ea1f
Revises: 2747492a479e
Create Date: 2023-08-15 23:00:22.720511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d496e50ea1f'
down_revision = '2747492a479e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.Unicode(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
